FORMAT: 1A
HOST: https://api.sharix.tech/

# Sharix API
The Sharix API is for those interested in playing millions of movies and shows in your application. The Sharix API can be used to retrieve and use data and/or sources programmatically.

# Legal Disclaimer
The Sharix API and the distribution of the Sharix API is not illegal and does not violate DMCA laws. However, use of the Sharix API may be illegal in your region. Check your local laws and regulations regarding the playback of potentially copyrighted content. The operators will not tolerate the Sharix API being used for anything illegal in any state, region, country or planet. Please use the Sharix API at your own risk.

# Sharix TV App
The Sharix API has been fully implemented in the [**Sharix TV App**](https://sharix.tech) which runs across all devices. These include iOS, iPadOS, tvOS, macOS and Airplay.

# Status 
The status of the Sharix API services can be checked at [**status.sharix.tech**](https://status.sharix.tech).

# Issues 
If you encounter problems using the Sharix API or the documentation is incomplete or incorrect, please file a issue on [**GitHub**](https://github.com/Boostvolt/sharix_tv_api/issues).

# API URL
The API should always be accessed over SSL.

```
https://api.sharix.tech
```

# Verbs
The API uses restful verbs.

| Verb | Description |
|---|---|
| `GET` | Select one or more items. Success returns `200` status code. |

# Dates
All dates will be GMT and returned in the ISO 8601 format like `2020-09-01T09:10:11.000Z`. Adjust accordingly in your app for the user's local timezone.

# Media Links
There are several ways to construct direct links to media on the Sharix API website. The website itself uses slugs so the URLs are more readable.

| Type | URL |
|---|---|
| `movie` | `/movies/:slug` |
| `show` | `/shows/:slug` |

# Data Structures

## Movie
_id: (string, required)
imdb_id: (string, required)
title: (string, required)
year: (number, required)
slug: (string, optional)
synopsis: (string, required)
runtime: (number, required)
released: (number,  required)
trailer: (string,  required)
certification: (string,  required)
clusters: (MovieLanguages, required)
genres: (array[string], required)
images: (Images, required)
rating: (Rating, required)
type: (string, required)
language: (string,  optional)

# Group Movies

## All [/movies]

### Get all movies [GET]
Returns an array of all available movies.

  + Request (application/json)

      + Headers

            sharix-api-authorization:[access_token]
            sharix-api-version: 1
            
  + Response 200 (application/json; charset=utf-8)

      + Body

            ["movies/1","movies/2","movies/3","movies/4","movies/5","movies/6","movies/7","movies/8","movies/9","movies/10"]

      + Attributes (array[string])

## Random [/random/movie]

### Get random movie [GET]
Returns details a random movie.
  
  + Request (application/json)

    + Headers

            sharix-api-authorization:[access_token]
            sharix-api-version: 1
  
  + Response 200 (application/json; charset=utf-8)

      + Body

            {"_id":"UniqueString1","imdb_id":"UniqueString1","title":"String","year":0,"slug":"String","synopsis":"String","runtime":0,"rating":{"percentage":0,"watching":0,"votes":0},"images":{"banner":"String","fanart":"String","poster":"String"},"genres":["String"],"type":"String","language":"String","released":0,"trailer":"String","certification":"String","clusters":{"en":{"1080p":{"provider":"String","filesize":"String","size":0,"peer":0,"seed":0,"url":"String"},"720p":{"provider":"String","filesize":"String","size":0,"peer":0,"seed":0,"url":"String"}}}}

      + Attributes (Movie)

## Sort [/movies/{page}{?sort}]
Movies can be sorted according to the following criteria:
- Trending
- Popularity
- Last added
- Top rated
- Year of publication

### Get movies by sort criteria [GET]
Returns an array of movies that correspond to the selected sort criteria.
  + Parameters
      + page (number, `1`) - The page of the content you want.
      + sort (string, `trending`) - Sort the list of content.
        + Values
              + `trending`
              + `popular`
              + `released`
              + `rating`
              + `year`

  + Request (application/json)

    + Headers

            sharix-api-authorization:[access_token]
            sharix-api-version: 1

  + Response 200 (application/json; charset=utf-8)

      + Body

            [{"_id":"UniqueString1","imdb_id":"UniqueString1","title":"String","year":0,"slug":"String","synopsis":"String","runtime":0,"rating":{"percentage":0,"watching":0,"votes":0},"images":{"banner":"String","fanart":"String","poster":"String"},"genres":["String"],"type":"String","language":"String","released":0,"trailer":"String","certification":"String","clusters":{"en":{"1080p":{"provider":"String","filesize":"String","size":0,"peer":0,"seed":0,"url":"String"},"720p":{"provider":"String","filesize":"String","size":0,"peer":0,"seed":0,"url":"String"}}}}]

      + Attributes (array[Movie])

## Genres [/movies/{page}{?genre}]
Movies can be requested according to the following genres:
- Adventure
- Action
- Animation
- Documentation
- Drama
- Family
- Fantasy
- Comedy
- Horror
- Crime
- Music
- Mystery
- Romantic
- Science Fiction
- Thriller
- Western


### Get movies by genre [GET]
Returns an array of movies that correspond to the selected genre.
  + Parameters
      + page (number, `1`) - The page of the content you want.
      + genre (string, `adventure`) - Filter on a genre.
         + Values
              + `adventure`
              + `action`
              + `animation`
              + `documentation`
              + `drama`
              + `family`
              + `fantasy`
              + `comedy`
              + `horror`
              + `crime`
              + `music`
              + `mystery`
              + `romantic`
              + `science-fiction`
              + `trhiller`
              + `western`
  
  + Request (application/json)

    + Headers

            sharix-api-authorization:[access_token]
            sharix-api-version: 1
            
  + Response 200 (application/json; charset=utf-8)

      + Body

            [{"_id":"UniqueString1","imdb_id":"UniqueString1","title":"String","year":0,"slug":"String","synopsis":"String","runtime":0,"rating":{"percentage":0,"watching":0,"votes":0},"images":{"banner":"String","fanart":"String","poster":"String"},"genres":["String"],"type":"String","language":"String","released":0,"trailer":"String","certification":"String","clusters":{"en":{"1080p":{"provider":"String","filesize":"String","size":0,"peer":0,"seed":0,"url":"String"},"720p":{"provider":"String","filesize":"String","size":0,"peer":0,"seed":0,"url":"String"}}}}]

      + Attributes (array[Movie])

## Search [/movies/{page}{?keywords}]
Movies can be requested according to specific search keywords.
### Get movies by keyword [GET]
Returns an array of movies that correspond to the search keyword.
  + Parameters
      + page (number, `1`) - The page of the content you want.
      + keywords (string, `Star Wars`) - Search based on keywords.

  + Request (application/json)

    + Headers

            sharix-api-authorization:[access_token]
            sharix-api-version: 1

  + Response 200 (application/json; charset=utf-8)

      + Body

            [{"_id":"UniqueString1","imdb_id":"UniqueString1","title":"String","year":0,"slug":"String","synopsis":"String","runtime":0,"rating":{"percentage":0,"watching":0,"votes":0},"images":{"banner":"String","fanart":"String","poster":"String"},"genres":["String"],"type":"String","language":"String","released":0,"trailer":"String","certification":"String","clusters":{"en":{"1080p":{"provider":"String","filesize":"String","size":0,"peer":0,"seed":0,"url":"String"},"720p":{"provider":"String","filesize":"String","size":0,"peer":0,"seed":0,"url":"String"}}}}]

      + Attributes (array[Movie])

## Details [/movie/{imdb_id}]
Details about a movie can be requested using the IMDb ID.
### Get movie details [GET]
Returns details about a single movie based on the given IMDb ID.
  + Parameters
      + imdb_id (string, `tt0468569`) - The IMDb ID of the movie you want details on.
  
  + Request (application/json)

    + Headers

            sharix-api-authorization:[access_token]
            sharix-api-version: 1
  
  + Response 200 (application/json; charset=utf-8)

      + Body

            {"_id":"UniqueString1","imdb_id":"UniqueString1","title":"String","year":0,"slug":"String","synopsis":"String","runtime":0,"rating":{"percentage":0,"watching":0,"votes":0},"images":{"banner":"String","fanart":"String","poster":"String"},"genres":["String"],"type":"String","language":"String","released":0,"trailer":"String","certification":"String","clusters":{"en":{"1080p":{"provider":"String","filesize":"String","size":0,"peer":0,"seed":0,"url":"String"},"720p":{"provider":"String","filesize":"String","size":0,"peer":0,"seed":0,"url":"String"}}}}

      + Attributes (Movie)

# Group Shows

# Group Subtitles

# Group Account